# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c54699bc09b43dd2c8c4e4f3f2be72535cedd6c5e2b878da7f76f3e5d113e9e28b2864cb35d55fcd8156f2c00310154fe94afc3c26bd56911204a1349b3439b

test:
  secret_key_base: bd7a17142dc0adaf38e477711991d68c8df537f203f66851f909b85744c5ac6966c4edf708094b6b37151bfa97d8cf1d071c4d44ab2790656339048a9a8ae86b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
